version: '3.5' 

services: 
  backend: 
    build: ./backend/
    container_name: web-backend
    ports:
      - 8080:8080
    command: ./server

  frontend:
    build: ./frontend/ 
    container_name: web-frontend
    ports:
      - 5000:5000
    command: serve -s -l 5000 build