version: '3.5' 

services: 

    simple-web-service: 
      image: devopsdockeruh/simple-web-service
      volumes: 
        - ./logs.txt:/usr/src/app/text.log
      container_name: simple-web-service