version: '3.5'

services:
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
     - ./database:/var/lib/postgresql/data
  
  proxy:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
     - 80:80
    depends_on:
      - frontend
      - backend 

  backend:
    build: ./backend/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - REQUEST_ORIGIN=*
    depends_on:
      - db

  frontend:
    build: ./frontend/
    ports:
      - 5000:5000
    depends_on:
      - backend