version: '3.5' 

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: goback
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backenddb
    container_name: db_backend
    volumes:
      - ./database:/var/lib/postgresql/data
 
  backend: 
    build: ./backend/
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=goback
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=backenddb
    command: ./server
    depends_on:
      - db

  frontend:
    build: ./frontend/ 
    ports:
      - 5000:5000
    command: serve -s -l 5000 build