version: '3.5' 

services:
  redis:
    image: redis

  backend: 
    build: ./material-applications/example-backend/
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis

  frontend:
    build: ./material-applications/example-frontend/
    ports:
      - 5000:5000